### ISSUE TITLE
pycocotools starts with index 1

### ISSUE THREAD

**Issue by labintsev** [LSH9832/edgeyolo#12]
Hi guys! Thanks for your great job!

I have evaluate my custom one-class (pedestrian) dataset (visdrone format) and have -1 COCO metrics values, because pycocotool class indexes starts with 1. Index 0 means no-object. 
I fix it locally, and now it works fine for me.
But  may be all the pedestrians are not included in your COCO evaluation? 

Add this line: 
`coco_evaluator.py  
242:    logger.info(f'cocoGT {cocoGt.anns[1]} CatIds: {cocoGt.cats}')`

And get result:

> cocoGT {'segmentation': [], 'area': 598.0, 'iscrowd': 0, 'image_id': 0, 'bbox': [440.0, 248.0, 13.0, 46.0], **'category_id': 0,** 'id': 1} , ...
CatIds: {**1**: {'supercategory': 'pedestrian', **'id': 1**, 'name': 'pedestrian'}, ...

**Comment by LSH9832** [comment]
thanks, we do make a mistake converting to coco category ids, now it starts with index 0 and gets the correct results.
