### ISSUE TITLE
在detector.py中并没有找到utils中的postprocess, get_model_info，请问可以更新一下库吗

### ISSUE THREAD

**Issue by wktxdy** [LSH9832/edgeyolo#17]
如题。

**Comment by LSH9832** [comment]
get_model_info  ->  edgeyolo/utils/model_utils.py
postprocess -> edgeyolo/utils/boxes.py

**Comment by wktxdy** [comment]
> get_model_info -> edgeyolo/utils/model_utils.py postprocess -> edgeyolo/utils/boxes.py

感谢！
