### ISSUE TITLE
why not use enhance_mosaic in training COO or DOTA?

### ISSUE THREAD

**Issue by 1224wxwx** [LSH9832/edgeyolo#23]
Hi, thanks for share your azmazing work.

In [train_coco.yaml](https://github.com/LSH9832/edgeyolo/blob/main/params/train/train_coco.yaml) and [train_dota.yaml](https://github.com/LSH9832/edgeyolo/blob/main/params/train/train_dota.yaml), I notice that the setting of enhance_mosaic is set to False. 

According to your paper this method could effectively increases the image richness. Could you please tell me why don't you use enhance_mosaic? 

Thanks!

**Comment by LSH9832** [comment]
It works well when the number of labels is not enough in single image, but doesn't when it is already enough. It surely can be used when training models in coco dataset, but need some extra tricks to ensure its effect, so we chose to set it disabled for others to use.

Currently our paper and source code are not the final version actually, we will still update them serveral times before next year.
