### ISSUE TITLE
many false positives

### ISSUE THREAD

**Issue by taotaoland** [LSH9832/edgeyolo#25]
many false positives
![20230423161755](https://user-images.githubusercontent.com/13161302/233828327-1dcc8d7d-1cd7-4665-98dd-66a8c621e4be.png)

**Comment by LSH9832** [comment]
we strengthen the detection of small objects in our training, so our model trained on VisDrone is more suitable for high-altitude small object detection, **and inevitably**, there will be more false positives if your camera's altitude is not high enough(as high as most images in VisDrone dataset).

**Comment by taotaoland** [comment]
> we strengthen the detection of small objects in our training, so our model trained on VisDrone is more suitable for high-altitude small object detection, **and inevitably**, there will be more false positives if your camera's altitude is not high enough(as high as most images in VisDrone dataset).

Thank you for your reply, how should I solve this problem?

**Comment by taotaoland** [comment]
> > we strengthen the detection of small objects in our training, so our model trained on VisDrone is more suitable for high-altitude small object detection, **and inevitably**, there will be more false positives if your camera's altitude is not high enough(as high as most images in VisDrone dataset).
> 
> Thank you for your reply, how should I solve this problem?

"Can you give me some suggestions, please?

**Comment by LSH9832** [comment]
the most fundamental reason is that VisDrone dataset does not match your application scenario. I think model trained on COCO dataset might work and you can try it first, but the best way is to find a more suitable dataset and retrain the model.

**Comment by taotaoland** [comment]
thank you very much.
