### ISSUE TITLE
请问visdrone2019的coco是怎么设置的

### ISSUE THREAD

**Issue by JiSeaSuperM** [LSH9832/edgeyolo#30]
我按相同的形式把VisDrone2019MOT的转换coco了一波。用预训练权重训练的时候发现，精度在往下跌，15个epoch的时候直接全是0了。我看了下你们提供的VisDrone_coco中的json，里面categories包含"ignored regions"和"others"，但是category_id只有0~9。然后按照默认配置num_classes也被设置为10。

**Comment by LSH9832** [comment]
训练时"ignored regions"和"others"是删了的，精度往下跌就不清楚是什么问题了，你拿[tools/load_dataset.py](https://github.com/LSH9832/edgeyolo/blob/main/demo/load_dataset.py) 看看你的数据集导入后标签对不对，有可能是标签的问题

**Comment by JiSeaSuperM** [comment]
> 训练时"ignored regions"和"others"是删了的，精度往下跌就不清楚是什么问题了，你拿[tools/load_dataset.py](https://github.com/LSH9832/edgeyolo/blob/main/demo/load_dataset.py) 看看你的数据集导入后标签对不对，有可能是标签的问题

啊，那我可能下那个资源的时候有点早，那个json文件里categories还包含"ignored regions"和"others"，我再看看

**Comment by LSH9832** [comment]
不不不，配置文件里有，但是代码将标签导入内存的时候会删

**Comment by LSH9832** [comment]
你进文件[edgeyolo/data/datasets/visdrone.py](https://github.com/LSH9832/edgeyolo/blob/main/edgeyolo/data/datasets/visdrone.py)看看标签是怎么导入的就清楚了

**Comment by JiSeaSuperM** [comment]
> 你进文件[edgeyolo/data/datasets/visdrone.py](https://github.com/LSH9832/edgeyolo/blob/main/edgeyolo/data/datasets/visdrone.py)看看标签是怎么导入的就清楚了，不过如果转coco的话需要你在数据集中的json中手动删掉这两项

好的，我检查了我的文件一遍，之前我的json就是没有用ig和other的。但是那个也不行，我看看其他哪里出问题了

**Comment by JiSeaSuperM** [comment]
> 训练时"ignored regions"和"others"是删了的，精度往下跌就不清楚是什么问题了，你拿[tools/load_dataset.py](https://github.com/LSH9832/edgeyolo/blob/main/demo/load_dataset.py) 看看你的数据集导入后标签对不对，有可能是标签的问题

我用这个看了一下，前面几张发现检测框偏移的厉害，就其中几张对上了，这是啥情况，这标签的值也是官方的数据注释。tools/load_dataset.py这里面的代码我就只改了读取我的那个yaml

**Comment by LSH9832** [comment]
那就是标签的问题，这你就自己检查转换的代码然后debug吧

**Comment by JiSeaSuperM** [comment]
> 那就是标签的问题，这你就自己检查转换的代码然后debug吧

OK。因为我之前转换MOT的val然后测试过，然后发现精度差不多，以为没啥问题了。

**Comment by JiSeaSuperM** [comment]
OK成功了，感谢帮助，转换代码没有问题，之前是在我自己电脑转换的没事，在服务器上转换出现了缺漏，现在我直接在自己电脑转就没事了。太玄学了
