### ISSUE TITLE
关于detect.py

### ISSUE THREAD

**Issue by JusticeLin** [LSH9832/edgeyolo#49]
非常感谢您的分享。我在运行evaluate的时候是没问题的，训练结束后想要进行detect，但是总是报错，错误如下，请问是我的环境配置出错了吗，方便提供下python，pytorch，cuda，opencv的版本吗，我这里可能是opencv出了问题，但是尝试了许多版本都没办法进行预测。
After re-parameterization: Params: 40.47M, Gflops: 280.00
After re-parameterization: Params: 40.47M, Gflops: 280.00
After re-parameterization: Params: 40.47M, Gflops: 280.00
After re-parameterization: Params: 40.47M, Gflops: 280.00
After re-parameterization: Params: 40.47M, Gflops: 280.00
After re-parameterization: Params: 40.47M, Gflops: 280.00
242.7ms  average:242.7msqt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/lzy30/anaconda3/envs/edgeyolo/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

**Comment by LSH9832** [comment]
detect.py里面有cv2.imshow的，必须有图形化界面的操作系统才能正常使用。二是opencv确实会有概率与pyqt库起冲突，可以pip uninstall pyqt5 pyside2后再试试
