### ISSUE TITLE
AnchorFreeDetect参数融合

### ISSUE THREAD

**Issue by yoouaicv** [LSH9832/edgeyolo#9]
将YOLOXDetect切换为AnchorFreeDetect，其中的ia参数融合报错。
code：
for i in range(len(self.m)):
            c1, c2, _, _ = self.m[i].weight.shape
            c1_, c2_, _, _ = self.ia[i].implicit.shape
            self.m[i].bias += torch.matmul(self.m[i].weight.reshape(c1, c2),
                                           self.ia[i].implicit.reshape(c2_, c1_)).squeeze(1)
Error：
ValueError: Cannot assign non-leaf Tensor to parameter 'bias'. Model parameters must be created explicitly. To express 'bias' as a function of another Tensor, compute the value in the forward() method.

**Comment by LSH9832** [comment]
AnchorFreeDetect是最早的版本，代码更新后不适配了，这个检测头效果不太好
